### ISSUE TITLE
Improve example 

### ISSUE THREAD

**Issue by genestealer** [ajobbins/AHK-Teams-Presence#1]
Firstly, thank you for sharing. I have managed to get this to work after some fiddling. 
Please can you add an example URL to the "WebhookURI" 
As it took me a while and originally edited your code to use WinHTTP.SetRequestHeader("Authorization", "Bearer etc etc ") and set a state, as I did not know about trigging automations using webhooks. I have revered back now, but would be handy to add that as a comment in the .ahk file.
E.G.
https://your-home-assistant:8123/api/webhook/some_hook_id

**Comment by ajobbins** [comment]
Thanks for the feedback, will look to update.

I also have a newer example in testing that is more reliable - using the text from the Tray icon rather than the icon itself (which can be read without it be visible on the screen) so will look to update this here once I have a chance to do some more testing.

**Comment by genestealer** [comment]
That's awesome. Thank you again for your hard work.

**Comment by ajobbins** [comment]
This script has now been updated with the example as requested, but also moved to reading from the Teams log file which is far more reliable (But please see the to do section)
